apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fargate-cluster
  region: eu-west-1

privateCluster:
  enabled: false

nodeGroups:
  - name: ng-default
    instanceType: t3.micro
    minSize: 2
    maxSize: 4
    desiredCapacity: 2

iamIdentityMappings:
  - arn: arn:aws:iam::${ACCOUNT_NUMBER}:role/UPDATE-EKS-DEPLOYMENT-ROLE
    username: update-eks-deployments-user
    noDuplicateARNs: true # prevents shadowing of ARNs

cloudWatch:
  clusterLogging:
    enableTypes:
      - "authenticator"
    logRetentionInDays: 1


