apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-cluster
  region: eu-west-1

privateCluster:
  enabled: false

managedNodeGroups:
  - name: ng-default
    instanceType: t2.small
    minSize: 2
    maxSize: 5
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        autoScaler: true

iamIdentityMappings:
  - arn: arn:aws:iam::${ACCOUNT_NUMBER}:role/UPDATE-EKS-DEPLOYMENT-ROLE
    username: update-eks-deployments-user
    noDuplicateARNs: true # prevents shadowing of ARNs

cloudWatch:
  clusterLogging:
    enableTypes:
      - "authenticator"
    logRetentionInDays: 1


