kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: update-eks-deployments-role-biding
  namespace: default
subjects:
- kind: User
  name: update-eks-deployments-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: update-eks-deployments-role
  apiGroup: rbac.authorization.k8s.io