kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: update-eks-deployments-role
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "apply"]